language: python
sudo: required
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
- pypy3
services:
- docker
before_install:
- |
  docker run -d -p 4001:4001 -p 2380:2380 \
    quay.io/coreos/etcd \
    --listen-client-urls=http://0.0.0.0:4001 \
    --advertise-client-urls=http://127.0.0.1:4001 \
    --listen-peer-urls=http://0.0.0.0:2380
install:
- pip install -e .
- pip install coveralls
script:
- coverage run --source=etc setup.py test
after_success:
- coveralls
